run_mode: train # train analyse

resume_training: false
experiment_dir: mobile_experiments
experiment_description: penm00_1001_lstm2_S20         
dataset_path: /home/notebook/data/group/intention_rec/app-series/PENM00_Sqlite_W1001_S20/

dataloader_code: sqlite_dummy     # dummy_app_lmdb   dummy_app
from_memory: false
num_workers: 10
batch_size: &batch_size 256
train_batch_size: *batch_size
val_batch_size:  *batch_size
test_batch_size: *batch_size
class_num: &class_num 5000
series_len: 1001

trainer_code: lstm
device: cuda
device_idx: '0'
optimizer: Adam
weight_decay: 0.0001
enable_lr_schedule: false
lr: 0.001

num_epochs: 14
ks: [1, 2, 3, 4, 5]
metrics_list: ['Top@1','Top@2','Top@3','Top@4' ,'Top@5']
best_metric: Top@5

ignore_class: [0]
dataset_wechat_ratio: 0.

model_code: lstm
dropout_p: 0.1
embedding_dim: &embedding_dim 64
d_model: *embedding_dim
n_layers: 2

task_hidden_units: [*class_num]
activation: relu
task: multiclass

