run_mode: train # train analyse

resume_training: false
experiment_dir: mobile_experiments
experiment_description: peem00_101_mlp_S20
dataset_path: /home/notebook/data/group/intention_rec/app-series/PEEM00_Sqlite_W101_S20

dataloader_code: sqlite_dummy
from_memory: false
num_workers: 8
# batch_size: &batch_size 128
train_batch_size: 256
val_batch_size:  1024
test_batch_size: 1024
class_num: &class_num 5000
series_len: 101

trainer_code: e2e
device: cuda
device_idx: '0'
optimizer: Adam
weight_decay: 0.0001
enable_lr_schedule: false
lr: 0.001

num_epochs: 14
ks: [1, 2, 3, 4, 5]
metrics_list: ['Top@1', 'Top@2', 'Top@3', 'Top@4', 'Top@5']
best_metric: Top@5

ignore_class: [0]
dataset_wechat_ratio: 0.

model_code: mlp
dropout_p: 0.0
embedding_dim: 64

task_hidden_units: [256, 64, *class_num]
activation: relu
task: multiclass

