run_mode: train # train analyse

resume_training: false
experiment_dir: debug_experiments
experiment_description: peem00_101_mlp_S20_2022-03-01_0_copy
dataset_path: /home/notebook/data/group/intention_rec/app-series/PEEM00/data/huanggang_sample_data/sqlite_data_itself/data.raw.wechat.2000.1200_W101_S1

dataloader_code: sqlite_dummy
from_memory: false
num_workers: 8
batch_size: &batch_size 32
train_batch_size: *batch_size
val_batch_size:  *batch_size
test_batch_size: *batch_size
class_num: &class_num 51
series_len: 101

trainer_code: e2e
device: cuda
device_idx: '0'
optimizer: Adam
weight_decay: 0.0001
enable_lr_schedule: false
lr: 0.001

num_epochs: 14
ks: [1, 2, 3, 4, 5]
metrics_list: ['Top@1', 'Top@2', 'Top@3', 'Top@4', 'Top@5']
best_metric: Top@5

ignore_class: [0]
dataset_wechat_ratio: 0.

model_code: mlp
dropout_p: 0.0
embedding_dim: 64

task_hidden_units: [256, 64, *class_num]
activation: relu
task: multiclass

