run_mode: train # train analyse

resume_training: true
experiment_dir: mobil_experiments
experiment_description: peem00_101_pctran_S20_2022-02-24_1
dataset_path: /home/notebook/data/group/intention_rec/app-series/123One_Sqlite_W101_S1/

dataloader_code: sqlite_dummy
from_memory: false
num_workers: 8
batch_size: &batch_size 32
train_batch_size: *batch_size
val_batch_size:  *batch_size
test_batch_size: *batch_size
class_num: &class_num 5000
series_len: 101
sub_k_list: [20, 20]
epsilon: 0.01

trainer_code: pc_trans
device: cuda
device_idx: '0'
optimizer: Adam
weight_decay: 0.0001
enable_lr_schedule: false
lr: 0.001

num_epochs: 8
ks: [1, 2, 3, 4, 5]
metrics_list: ['Top@1','Top@2','Top@3','Top@4' ,'Top@5']
best_metric: Top@5

ignore_class: [0]
dataset_wechat_ratio: 0.

model_code: pc_trans
dropout_p: 0.1
embedding_dim: &embedding_dim 64
d_model: *embedding_dim
n_layers: 2
n_heads: 4

task_inputs_series_len: 1
task_hidden_units: [*class_num]
activation: relu
task: multiclass

