run_mode: train

resume_training: false
experiment_dir: debugs
experiment_description: mnist

dataloader_code: mnist
batch: &batch 128
train_batch_size: *batch
val_batch_size:  *batch
test_batch_size: *batch

trainer_code: image_classification
device: cuda
device_idx: "0"
optimizer: Adam
weight_decay: 0.0
enable_lr_schedule: false
lr: 0.001

num_epochs: 5

ks: [1, 5]
metrics_list: ['Top@1', 'Top@5']
best_metric: Top@1

model_code: mnist_dnn
dropout_p: 0.0
dnn_input_units: 784 
dnn_hidden_units: [64, 10]
activation: relu
task: binary
task_label: label

